In [88]:
import pandas as pd
from pathlib import Path

In [ ]:
from pathlib import Path        # Se comprueba la ruta real donde están los CSV.

ruta = Path("..") / "Análisis de Operaciones Logísticas" / "Data" / "dataset"

print(ruta.resolve())   # Para comprobar la ruta completa
print(ruta.exists())
print(list(ruta.glob("*.csv")))

E:\HECTICO DOCUMENTOS\DOCUMENTOS\SUPERACION\IT ACADEMY\ESPECIALIZACION\PYTHON\PROYECTO FINAL\Análisis de Operaciones Logísticas\Data\dataset
True
[WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/customers.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/delivery_events.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/drivers.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/driver_monthly_metrics.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/facilities.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/fuel_purchases.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/loads.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/maintenance_records.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/routes.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/safety_incidents.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/trailers.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/trips.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/trucks.csv'), WindowsPath('../Análisis de Operaciones Logísticas/Data/dataset/truck_utilization_metrics.csv')]

Se cargan todos los archivos CSV contenidos en la carpeta dataset en un diccionario de DataFrames. Cada clave corresponde al nombre del archivo (sin la extensión .csv) y el valor es el DataFrame asociado. Esta estructura facilita la gestión de múltiples tablas durante el análisis.

In [8]:
ruta = Path("..") / "Análisis de Operaciones Logísticas" / "Data" / "dataset"

dataframes = {}

for archivo in ruta.glob("*.csv"):
    dataframes[archivo.stem] = pd.read_csv(archivo)

In [ ]:
list(dataframes.keys())           # Se genera lista con los nombres de los archivos que tenemos que serían las claves del diccionario.

['customers',
 'delivery_events',
 'drivers',
 'driver_monthly_metrics',
 'facilities',
 'fuel_purchases',
 'loads',
 'maintenance_records',
 'routes',
 'safety_incidents',
 'trailers',
 'trips',
 'trucks',
 'truck_utilization_metrics']

Para facilitar la lectura del código, cada DataFrame se asigna a una variable con el mismo nombre que su archivo de origen.

In [10]:
customers = dataframes['customers']
delivery_events = dataframes['delivery_events']
drivers = dataframes['drivers']
driver_monthly_metrics = dataframes['driver_monthly_metrics']
facilities = dataframes['facilities']
fuel_purchases = dataframes['fuel_purchases']
loads = dataframes['loads']
maintenance_records = dataframes['maintenance_records']
routes = dataframes['routes']
safety_incidents = dataframes['safety_incidents']
trailers = dataframes['trailers']
trips = dataframes['trips']
trucks = dataframes['trucks']
truck_utilization_metrics = dataframes['truck_utilization_metrics']

Se desarrolla una exploración inicial para poder ver como están formados cada uno de los dataframes, así como la calidad de los datos con los cuales vamos a trabajar.

In [11]:
customers.head()

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [13]:
customers.describe()

       credit_terms_days  annual_revenue_potential
count         200.000000              2.000000e+02
mean           37.650000              2.688237e+06
std            17.078815              1.454957e+06
min            15.000000              1.016410e+05
25%            30.000000              1.405872e+06
50%            30.000000              2.784584e+06
75%            60.000000              3.859272e+06
max            60.000000              4.990599e+06

In [14]:
customers.dtypes

customer_id                 object
customer_name               object
customer_type               object
credit_terms_days            int64
primary_freight_type        object
account_status              object
contract_start_date         object
annual_revenue_potential     int64
dtype: object

In [16]:
customers.isnull().sum()

customer_id                 0
customer_name               0
customer_type               0
credit_terms_days           0
primary_freight_type        0
account_status              0
contract_start_date         0
annual_revenue_potential    0
dtype: int64

In [19]:
delivery_events.head()

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
4,EVT00000005,LOAD00000003,TRIP00000003,Pickup,FAC00001,2022-01-01 08:00:00.000000,2022-01-01 07:28:02.169634,83,True,Columbus,OH

In [21]:
delivery_events.dtypes

event_id              object
load_id               object
trip_id               object
event_type            object
facility_id           object
scheduled_datetime    object
actual_datetime       object
detention_minutes      int64
on_time_flag            bool
location_city         object
location_state        object
dtype: object

In [23]:
delivery_events.isnull().sum()

event_id              0
load_id               0
trip_id               0
event_type            0
facility_id           0
scheduled_datetime    0
actual_datetime       0
detention_minutes     0
on_time_flag          0
location_city         0
location_state        0
dtype: int64

In [26]:
drivers.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [27]:
drivers.dtypes

driver_id            object
first_name           object
last_name            object
hire_date            object
termination_date     object
license_number       object
license_state        object
date_of_birth        object
home_terminal        object
employment_status    object
cdl_class            object
years_experience      int64
dtype: object

In [28]:
drivers.isnull().sum()

driver_id              0
first_name             0
last_name              0
hire_date              0
termination_date     124
license_number         0
license_state          0
date_of_birth          0
home_terminal          0
employment_status      0
cdl_class              0
years_experience       0
dtype: int64

In [29]:
driver_monthly_metrics

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,2022-04-01,19,28127,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,2022-05-01,14,16071,36256.82,6.35,2573.1,0.214,6.8
...,...,...,...,...,...,...,...,...,...
4459,DRV00150,2024-08-01,22,33432,68220.59,6.56,5163.7,0.591,7.4
4460,DRV00150,2024-09-01,25,38537,73609.79,6.34,6195.5,0.360,7.0
4461,DRV00150,2024-10-01,27,38919,86802.35,6.53,6044.6,0.370,6.5
4462,DRV00150,2024-11-01,19,24256,51483.57,6.63,3708.8,0.368,6.2
4463,DRV00150,2024-12-01,14,21484,45774.78,6.33,3420.9,0.429,6.2

In [30]:
driver_monthly_metrics.dtypes

driver_id                 object
month                     object
trips_completed            int64
total_miles                int64
total_revenue            float64
average_mpg              float64
total_fuel_gallons       float64
on_time_delivery_rate    float64
average_idle_hours       float64
dtype: object

In [31]:
driver_monthly_metrics.isnull().sum()

driver_id                0
month                    0
trips_completed          0
total_miles              0
total_revenue            0
average_mpg              0
total_fuel_gallons       0
on_time_delivery_rate    0
average_idle_hours       0
dtype: int64

In [35]:
facilities.head()

,facility_id,facility_name,facility_type,city,state,latitude,longitude,dock_doors,operating_hours
0,FAC00001,Houston Distribution Center,Cross-Dock,Houston,TX,29.7604,-95.3698,125,24/7
1,FAC00002,Kansas City Hub,Cross-Dock,Kansas City,MO,39.0997,-94.5786,33,7AM-7PM
2,FAC00003,Charlotte Distribution Center,Distribution Center,Charlotte,NC,35.2271,-80.8431,138,24/7
3,FAC00004,Chicago Distribution Center,Distribution Center,Chicago,IL,41.8781,-87.6298,38,8AM-5PM
4,FAC00005,Indianapolis Hub,Distribution Center,Indianapolis,IN,39.7684,-86.1581,56,8AM-5PM

In [ ]:
facilities.dtypes

facility_id         object
facility_name       object
facility_type       object
city                object
state               object
latitude           float64
longitude          float64
dock_doors           int64
operating_hours     object
dtype: object

In [37]:
facilities.isnull().sum()

facility_id        0
facility_name      0
facility_type      0
city               0
state              0
latitude           0
longitude          0
dock_doors         0
operating_hours    0
dtype: int64

In [39]:
fuel_purchases.head()

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
1,FUEL00000002,TRIP00073723,TRK00013,NaN,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816
3,FUEL00000004,TRIP00008465,TRK00018,DRV00047,2022-04-20 00:00:00,Memphis,NY,130.7,3.579,467.78,FC776357
4,FUEL00000005,TRIP00069700,TRK00054,NaN,2024-06-13 09:00:00,Columbus,AZ,185.3,3.422,634.10,FC391024

In [40]:
fuel_purchases.dtypes

fuel_purchase_id     object
trip_id              object
truck_id             object
driver_id            object
purchase_date        object
location_city        object
location_state       object
gallons             float64
price_per_gallon    float64
total_cost          float64
fuel_card_number     object
dtype: object

In [41]:
fuel_purchases.isna().sum()

fuel_purchase_id       0
trip_id                0
truck_id            3880
driver_id           3988
purchase_date          0
location_city          0
location_state         0
gallons                0
price_per_gallon       0
total_cost             0
fuel_card_number       0
dtype: int64

In [ ]:
fuel_purchases[fuel_purchases['truck_id'].isna()]

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
11,FUEL00000012,TRIP00079405,NaN,DRV00085,2024-10-16 19:00:00,Los Angeles,WI,75.4,3.988,300.70,FC535781
37,FUEL00000038,TRIP00036457,NaN,DRV00020,2023-04-12 11:00:00,Indianapolis,TN,138.4,3.420,473.33,FC800413
111,FUEL00000112,TRIP00081338,NaN,DRV00142,2024-11-08 11:00:00,Kansas City,TN,64.3,3.476,223.51,FC971788
233,FUEL00000234,TRIP00058085,NaN,DRV00087,2024-01-19 18:00:00,Salt Lake City,MO,112.8,3.809,429.66,FC118946
352,FUEL00000353,TRIP00038469,NaN,DRV00037,2023-05-11 05:00:00,Kansas City,MN,86.8,3.437,298.33,FC647787
...,...,...,...,...,...,...,...,...,...,...,...
196229,FUEL00196230,TRIP00030711,NaN,DRV00088,2023-01-27 22:00:00,Dallas,WI,185.9,3.259,605.85,FC374293
196264,FUEL00196265,TRIP00029839,NaN,DRV00148,2023-01-19 13:00:00,Salt Lake City,WI,143.5,4.439,637.00,FC243338
196330,FUEL00196331,TRIP00009479,NaN,DRV00047,2022-05-03 08:00:00,Salt Lake City,MO,148.9,3.547,528.15,FC781292
196351,FUEL00196352,TRIP00025578,NaN,DRV00010,2022-11-22 15:00:00,Houston,CO,130.5,4.897,639.06,FC544183
196429,FUEL00196430,TRIP00028911,NaN,DRV00043,2023-01-06 17:00:00,Miami,TX,117.6,3.599,423.24,FC782603

In [47]:
loads.head()

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot

In [48]:
loads.dtypes

load_id                 object
customer_id             object
route_id                object
load_date               object
load_type               object
weight_lbs               int64
pieces                   int64
revenue                float64
fuel_surcharge         float64
accessorial_charges      int64
load_status             object
booking_type            object
dtype: object

In [49]:
loads.isna().sum()

load_id                0
customer_id            0
route_id               0
load_date              0
load_type              0
weight_lbs             0
pieces                 0
revenue                0
fuel_surcharge         0
accessorial_charges    0
load_status            0
booking_type           0
dtype: int64

In [51]:
loads.duplicated().sum()

np.int64(0)

In [53]:
maintenance_records.head()

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive
3,MAINT00000004,TRK00056,2022-01-02,Inspection,416522,2.8,298.80,67.48,366.28,Kansas City,34.6,Emergency Inspection
4,MAINT00000005,TRK00029,2022-01-02,Repair,179968,4.6,409.08,982.59,1391.67,Omaha,4.4,Emergency Repair

In [54]:
maintenance_records.dtypes

maintenance_id          object
truck_id                object
maintenance_date        object
maintenance_type        object
odometer_reading         int64
labor_hours            float64
labor_cost             float64
parts_cost             float64
total_cost             float64
facility_location       object
downtime_hours         float64
service_description     object
dtype: object

In [55]:
maintenance_records.isna().sum()

maintenance_id         0
truck_id               0
maintenance_date       0
maintenance_type       0
odometer_reading       0
labor_hours            0
labor_cost             0
parts_cost             0
total_cost             0
facility_location      0
downtime_hours         0
service_description    0
dtype: int64

In [58]:
routes.head()

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3

In [60]:
routes.duplicated().sum()

np.int64(0)

In [61]:
routes.isnull().sum()

route_id                  0
origin_city               0
origin_state              0
destination_city          0
destination_state         0
typical_distance_miles    0
base_rate_per_mile        0
fuel_surcharge_rate       0
typical_transit_days      0
dtype: int64

In [64]:
safety_incidents.head()

,incident_id,trip_id,truck_id,driver_id,incident_date,incident_type,location_city,location_state,at_fault_flag,injury_flag,vehicle_damage_cost,cargo_damage_cost,claim_amount,preventable_flag,description
0,INC00000001,TRIP00036079,TRK00006,DRV00006,2023-04-09 14:00:00,Moving Violation,Columbus,PA,True,False,12629.26,0.00,12629.26,True,Severe incident involving equipment
1,INC00000002,TRIP00032462,TRK00084,DRV00006,2023-02-19 11:00:00,Moving Violation,Columbus,NC,False,False,2700.70,14284.24,16984.94,False,Severe incident involving weather
2,INC00000003,TRIP00067583,TRK00106,DRV00119,2024-05-20 01:00:00,Customer Complaint,Seattle,OK,True,False,24302.32,0.00,24302.32,True,Minor incident involving traffic
3,INC00000004,TRIP00049128,TRK00085,DRV00134,2023-09-26 03:00:00,Equipment Damage,Kansas City,TN,True,False,4879.13,0.00,4879.13,True,Moderate incident involving equipment
4,INC00000005,TRIP00062884,TRK00014,DRV00133,2024-03-20 14:00:00,DOT Violation,Las Vegas,IN,False,False,14951.40,0.00,14951.40,False,Minor incident involving other driver

In [65]:
safety_incidents.dtypes

incident_id             object
trip_id                 object
truck_id                object
driver_id               object
incident_date           object
incident_type           object
location_city           object
location_state          object
at_fault_flag             bool
injury_flag               bool
vehicle_damage_cost    float64
cargo_damage_cost      float64
claim_amount           float64
preventable_flag          bool
description             object
dtype: object

In [66]:
safety_incidents.isnull().sum()

incident_id            0
trip_id                0
truck_id               1
driver_id              1
incident_date          0
incident_type          0
location_city          0
location_state         0
at_fault_flag          0
injury_flag            0
vehicle_damage_cost    0
cargo_damage_cost      0
claim_amount           0
preventable_flag       0
description            0
dtype: int64

In [67]:
trailers

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee
3,TRL00004,3910,Dry Van,53,2024,1AV544000060905105,2018-08-27,Active,New York
4,TRL00005,7524,Dry Van,53,2016,1AV170126369813275,2019-11-22,Active,Las Vegas
...,...,...,...,...,...,...,...,...,...
175,TRL00176,9109,Refrigerated,53,2015,1CV758072299883007,2018-08-17,Active,Miami
176,TRL00177,7703,Dry Van,53,2017,1AT732143483864478,2017-04-14,Active,Chicago
177,TRL00178,9056,Dry Van,53,2019,1CV418268282418473,2020-11-14,Active,Indianapolis
178,TRL00179,7809,Refrigerated,53,2016,1BV642386114313485,2016-03-02,Active,Houston
179,TRL00180,8272,Refrigerated,53,2015,1AU411294884657507,2018-12-23,Active,Columbus

In [68]:
trailers.dtypes

trailer_id          object
trailer_number       int64
trailer_type        object
length_feet          int64
model_year           int64
vin                 object
acquisition_date    object
status              object
current_location    object
dtype: object

In [70]:
trailers.duplicated().sum()

np.int64(0)

In [71]:
trips

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed
3,TRIP00000004,LOAD00000004,DRV00083,TRK00105,TRL00018,2022-01-01,717,11.1,110.3,6.50,9.6,Completed
4,TRIP00000005,LOAD00000005,DRV00044,TRK00076,TRL00054,2022-01-01,2243,35.0,328.9,6.82,11.6,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...
85405,TRIP00085406,LOAD00085406,DRV00005,TRK00029,TRL00058,2024-12-31,1023,19.2,157.9,6.48,7.5,Completed
85406,TRIP00085407,LOAD00085407,DRV00091,TRK00080,TRL00092,2024-12-31,749,14.9,124.6,6.01,7.3,Completed
85407,TRIP00085408,LOAD00085408,DRV00011,TRK00051,TRL00083,2024-12-31,1722,28.2,243.6,7.07,8.7,Completed
85408,TRIP00085409,LOAD00085409,DRV00094,TRK00073,TRL00137,2024-12-31,2758,47.9,415.4,6.64,4.8,Completed
85409,TRIP00085410,LOAD00085410,DRV00049,TRK00099,TRL00033,2024-12-31,1616,26.0,237.0,6.82,4.8,Completed

In [72]:
trips.dtypes

trip_id                   object
load_id                   object
driver_id                 object
truck_id                  object
trailer_id                object
dispatch_date             object
actual_distance_miles      int64
actual_duration_hours    float64
fuel_gallons_used        float64
average_mpg              float64
idle_time_hours          float64
trip_status               object
dtype: object

In [73]:
trips.isnull().sum()

trip_id                     0
load_id                     0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
trip_status                 0
dtype: int64

In [76]:
trips[trips[['driver_id', 'truck_id', 'trailer_id']].isna().any(axis=1)]

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
66,TRIP00000067,LOAD00000067,NaN,TRK00112,TRL00040,2022-01-01,2433,40.0,427.6,5.69,9.2,Completed
69,TRIP00000070,LOAD00000070,DRV00077,NaN,TRL00040,2022-01-01,711,14.2,105.5,6.74,9.7,Completed
73,TRIP00000074,LOAD00000074,DRV00051,NaN,TRL00141,2022-01-02,2937,51.6,428.8,6.85,9.7,Completed
87,TRIP00000088,LOAD00000088,DRV00078,NaN,TRL00072,2022-01-02,864,14.5,127.8,6.76,12.0,Completed
103,TRIP00000104,LOAD00000104,NaN,TRK00114,TRL00013,2022-01-02,1048,18.5,143.2,7.32,4.6,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...
85235,TRIP00085236,LOAD00085236,DRV00019,TRK00043,NaN,2024-12-29,1848,28.6,268.2,6.89,3.4,Completed
85239,TRIP00085240,LOAD00085240,NaN,TRK00053,TRL00149,2024-12-29,959,17.7,131.7,7.28,4.4,Completed
85240,TRIP00085241,LOAD00085241,DRV00070,TRK00108,NaN,2024-12-29,2732,51.1,470.2,5.81,9.2,Completed
85248,TRIP00085249,LOAD00085249,NaN,TRK00023,TRL00033,2024-12-30,1749,28.4,263.8,6.63,3.1,Completed
85365,TRIP00085366,LOAD00085366,NaN,TRK00099,TRL00095,2024-12-31,93,1.7,15.7,5.94,10.2,Completed

In [77]:
trucks

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150,Maintenance,Atlanta
3,TRK00004,3317,Freightliner,2015,1VV131945381692351,2017-06-17,8875,Diesel,200,Active,Salt Lake City
4,TRK00005,6731,Freightliner,2016,1FT822215709701985,2021-10-08,42042,Diesel,250,Maintenance,Miami
...,...,...,...,...,...,...,...,...,...,...,...
115,TRK00116,3449,International,2019,1MV446968103715126,2020-12-10,19653,Diesel,200,Active,Kansas City
116,TRK00117,9991,Peterbilt,2015,1FU939700479057712,2015-09-30,24671,Diesel,150,Inactive,New York
117,TRK00118,9647,Freightliner,2015,1NV150990165397549,2017-09-01,12050,Diesel,150,Inactive,Detroit
118,TRK00119,7934,Mack,2015,1MU171789091515507,2018-10-26,49441,Diesel,250,Inactive,Seattle
119,TRK00120,2821,Volvo,2017,1FT135731860465802,2019-03-06,35253,Diesel,250,Active,Kansas City

In [78]:
trucks.dtypes

truck_id                 object
unit_number               int64
make                     object
model_year                int64
vin                      object
acquisition_date         object
acquisition_mileage       int64
fuel_type                object
tank_capacity_gallons     int64
status                   object
home_terminal            object
dtype: object

In [79]:
trucks.isna().sum()

truck_id                 0
unit_number              0
make                     0
model_year               0
vin                      0
acquisition_date         0
acquisition_mileage      0
fuel_type                0
tank_capacity_gallons    0
status                   0
home_terminal            0
dtype: int64

In [80]:
truck_utilization_metrics

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,2022-01-01,22,39269,84792.02,6.78,2,4380.98,63.1,0.710
1,TRK00001,2022-02-01,27,40787,88809.05,6.23,0,0.00,0.0,0.964
2,TRK00001,2022-03-01,34,57422,120453.71,6.49,0,0.00,0.0,1.097
3,TRK00001,2022-04-01,20,34428,73531.28,6.50,2,3548.15,71.8,0.667
4,TRK00001,2022-05-01,16,20851,40791.53,6.38,1,1969.42,43.9,0.516
...,...,...,...,...,...,...,...,...,...,...
3307,TRK00120,2024-08-01,15,19931,47939.96,6.29,1,861.08,47.3,0.484
3308,TRK00120,2024-09-01,20,29583,64748.71,6.53,0,0.00,0.0,0.667
3309,TRK00120,2024-10-01,20,22229,49688.65,6.48,4,7341.49,131.9,0.645
3310,TRK00120,2024-11-01,25,38435,78366.23,6.39,1,1845.34,38.0,0.833
3311,TRK00120,2024-12-01,18,22642,50482.64,6.42,1,998.21,6.3,0.581

In [81]:
truck_utilization_metrics.dtypes

truck_id               object
month                  object
trips_completed         int64
total_miles             int64
total_revenue         float64
average_mpg           float64
maintenance_events      int64
maintenance_cost      float64
downtime_hours        float64
utilization_rate      float64
dtype: object

In [82]:
truck_utilization_metrics.isnull().sum()

truck_id              0
month                 0
trips_completed       0
total_miles           0
total_revenue         0
average_mpg           0
maintenance_events    0
maintenance_cost      0
downtime_hours        0
utilization_rate      0
dtype: int64

Conclusiones de la auditoría:
1- Se revisaron las 14 tablas del dataset.
2- No se detectaron valores duplicados significativos.
3- Se comprobó la existencia de valores nulos por tabla.
4- Se revisaron los tipos de datos de todas las variables.
5- Se detectaron que varias columnas que representan fecha y hora están almacenadas como object en vez de datetime64.
6- El dataset presenta una calidad adecuada para continuar con el análisis.

In [91]:
delivery_events.groupby('trip_id').size().head()

trip_id
TRIP00000001    2
TRIP00000002    2
TRIP00000003    2
TRIP00000004    2
TRIP00000005    2
dtype: int64

In [ ]:
delivery_events['event_type'].value_counts()     # Cuantos valores tiene la variable

event_type
Pickup      85410
Delivery    85410
Name: count, dtype: int64

In [ ]:
print("Loads únicos:", loads['load_id'].nunique())     # Comprobando relación entre Loads y trips
print("Trips únicos:", trips['load_id'].nunique())

Loads únicos: 85410
Trips únicos: 85410

In [95]:
loads.head()

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot